#
#  ____  ____ _____         _
# |  _ \/ ___|_   _|_ _ ___| | __
# | |_) \___ \ | |/ _` / __| |/ /
# |  _ < ___) || | (_| \__ \   <
# |_| \_\____/ |_|\__,_|___/_|\_\
#
# @author 若水
# 请不要随意更改配置， 否则会出现无法加载BUG
# 以下可以自定义按键名称与路径 按键数量为任务难度
自定义图片路径:
 §a第一章节: "textures/ui/recipe_book_icon"
 §b第二章节: "textures/ui/dust_selectable_1"
 §d第三章节: "textures/ui/dust_selectable_2"
 §6第四章节: "textures/ui/dust_selectable_3"
 §4第五章节: "textures/ui/ErrorGlyph"

#是否开启积分验证 如果开启则判断任务积分是否足以解锁下一级别任务 反之不检测
是否开启积分验证: true

#任务等级递增算法 没一级别提升 100 积分难度
任务等级增幅: 100

#初始级别分数(建议为0)
初始级别分数: 0

金币名称: "§e金币§r"

积分名称: "§b积分§r"

#是否使用EconomyAPI插件
enable-EconomyAPi: true

#当玩家正在进行任务时 在底部显示百分比
是否在底部显示任务进度: true

#关闭此选项后点击任务后将删除返回按键
是否增加任务界面返回按钮: true

#关闭此选项后玩家将无法执行/c
是否允许玩家执行c指令: true

#显示任务进度的底部类型 分为popup,tip,action
底部显示类型: "tip"

# 显示数量后将会在每个等级后均有每个任务状态的数量显示
# 但是这样会导致打开任务菜单卡顿
主页面是否显示数量: true

领取任务是否给予任务书: true

完成任务是否直接领取奖励: false

是否使用计分板: true

计分板:
 标题: "任务系统"
